name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: "1.12"
    - run: go build
